sudo: false

language: node_js

before_install:
  - export JOBS=max
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export JOBS=4; fi

os:
  - osx
  - linux

node_js:
  - 6
  - 8
  - 10

after_success: npm run coverage
