language: node_js

jobs:
  include:
    - os: linux
      node_js: 10
    - os: linux
      node_js: 12
    - os: linux
      node_js: 14
    - os: linux
      node_js: node
      env: [TEST_ELECTRON=1, BUILD_CMD=prebuild-linux, BUILD_GROUP=linux-x64]
      addons:
        apt:
          packages:
            - xvfb
      before_script:
        - export DISPLAY=':99.0'
        - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
    - os: osx
      node_js: 10
    - os: osx
      node_js: 12
    - os: osx
      node_js: 14
    - os: osx
      node_js: node
      env: [TEST_ELECTRON=1, BUILD_CMD=prebuild, BUILD_GROUP=darwin-x64]

before_install:
  - export JOBS=max
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export JOBS=4; fi

script:
  - npm run test
  - if [[ ! -z "$TEST_ELECTRON" ]]; then npm run test-electron; fi

after_success:
  - npm run coverage

before_deploy:
  - export ARCHIVE_NAME="${TRAVIS_TAG:-latest}-$BUILD_GROUP.tar.gz"
  - npm run $BUILD_CMD
  - file prebuilds/*/*
  - tar -zcvf "$ARCHIVE_NAME" -C prebuilds .

deploy:
  provider: releases
  draft: false
  api_key: "$PREBUILD_TOKEN"
  file: "$ARCHIVE_NAME"
  skip_cleanup: true
  on:
    tags: true
    condition: "! -z $BUILD_CMD"

notifications:
  email: false
